### ISSUE TITLE
Android Call Instance not persist

### ISSUE THREAD

**Issue by rub3n88** [foodji/capacitor-adyen#4]
Hi @Geschan 

I think there is a problem in the flow of requests from the capacitor to the plugin.

(I have only tested the Android version)

Process I have executed:
1. I download the payment methods from JS and complete the DropInOptions object.
2. I run presentDropIn next to the options object.
3. In the response, I receive the /payments information, with an "action" (threeDS2)
4. I execute the handleAction method with the "value" property with the "action" object.
5. The dropin interface keeps loading.

If I check the inspector, it can be seen that the identifier of the capacitor call is different in the handleAction request.

In iOS I have seen that keepAlive is used for capacitor calls, but in Android it is not being used.

I have tried to modify this in my Fork but it doesn't work for me either.

I have the same problem in dimissDropIn method. It tries to retrieve the lastPaymentResponse variable, but since the execution is performed in a different instance, this object is not set, and it generates an exception.

Am I running the process correctly?

**Comment by Geschan** [comment]
@rub3n88 I'm not sure what exactly is the problem. Maybe you can send me some example data?
What I can say regarding 3DS, that the current implementation does not support 3DSv1 when opening a seperate browser instance (as we did not implement any callback handling).
